### ISSUE TITLE
Installation assistance windows 10

### ISSUE THREAD

**Issue by itsMorio** [UserUnknownFactor/GIMP-ML#4]
I use gimp a lot so im very interested in trying this out, i followed the installation instructions as stated but with a lot of trial and errors i still cannot get this to work. The only information i can give to assist in this issue is the install.cmd files when ran spits out an error saying it failed to activate the created environment. I installed everything as said with no luck, i upgraded pip and virtualenv through python with no luck. So would appreciate some help in getting this installed correctly. Thanks.

**Comment by UserUnknownFactor** [comment]
Just ignore everything in the .cmd before `if ($cpuonly)` to use Python without setting environment then. It'll work with system level modules as well. Just run the following commands manually in a PowerShell console without `gimpenv3\Scripts\python.exe -m ` prefix. 

I used all recent modules and it worked fine after some minor code corrections in `onnxruntime`, but there may be some strangeness due to their ongoing changes.
